package io.github.nullifythis.android.flashcards

import kotlin.random.Random

object Words {

    enum class Options {
        GROUP_1,
        GROUP_2,
        GROUP_3,
        GROUP_4
    }

    fun createWordsForFlashCards(option: Options): List<String> {
        return when (option) {
            Options.GROUP_1 -> createSightWordListWithGroup(group1)
            Options.GROUP_2 -> createSightWordListWithGroup(group2)
            Options.GROUP_3 -> createSightWordListWithGroup(group3)
            Options.GROUP_4 -> createSightWordListWithGroup(group4)
        }
    }
    data class Group(
        val name: String,
        val words: Set<String>
    )

    private fun createSightWordListWithGroup(group: Group): List<String> {
        return randomizeListOfWords(group.words.toList())
    }

    private fun createSightWordListWithNewWords(): List<String> {
        return randomizeListOfWords(newWords.toList())
    }

    private fun createSightWordListWithAllWords(): List<String> {
        return randomizeListOfWords(allWords.toList()).take(35)
    }

    private fun createAlphabet(): List<String> {
        return ('A'..'Z').toList().map {
            it.toString() + it.plus(32)
        }
    }

    private fun createRandomizedAlphabet(): List<String> {
        return randomizeListOfWords(
            createAlphabet()
        )
    }

    fun createRandomizedNumbers(upperBound: Int): List<String> {
        return randomizeListOfWords(
            (0..upperBound).asIterable()
                .map { it.toString() }
        )
    }

    private fun randomizeListOfWords(listOfWords: List<String>): List<String> {
        val currentListOfWords = listOfWords.toMutableList()
        val randomizedList = mutableListOf<String>()
        while (currentListOfWords.isNotEmpty()) {
            val nextIndex = Random.nextInt(0, currentListOfWords.size)
            val nextWord = currentListOfWords.removeAt(nextIndex)
            randomizedList.add(nextWord)
        }
        return randomizedList
    }

    private val group1 = Group(
        name = "Group 1 - 50",
        words = setOf(
            "the",
            "of",
            "and",
            "a",
            "to",
            "in",
            "is",
            "you",
            "that",
            "it",
            "he",
            "was",
            "for",
            "on",
            "are",
            "as",
            "with",
            "his",
            "they",
            "I",
            "at",
            "be",
            "this",
            "have",
            "from",
            "or",
            "one",
            "had",
            "by",
            "words",
            "but",
            "not",
            "what",
            "all",
            "were",
            "we",
            "when",
            "your",
            "can",
            "said",
            "there",
            "use",
            "an",
            "each",
            "which",
            "she",
            "do",
            "how",
            "their",
            "if"
        )
    )

    private val group2 = Group(
        name = "Group 2 - 100",
        words = setOf(
            "will",
            "up",
            "other",
            "about",
            "out",
            "many",
            "then",
            "them",
            "these",
            "so",
            "some",
            "her",
            "would",
            "make",
            "like",
            "him",
            "into",
            "time",
            "has",
            "look",
            "two",
            "more",
            "write",
            "go",
            "see",
            "number",
            "no",
            "way",
            "could",
            "people",
            "my",
            "than",
            "first",
            "water",
            "been",
            "called",
            "who",
            "am",
            "its",
            "now",
            "find",
            "long",
            "down",
            "day",
            "did",
            "get",
            "come",
            "made",
            "may",
            "part"
        )
    )

    private val group3 = Group(
        name = "Group 3 - 150",
        words = setOf(
            "over",
            "new",
            "sound",
            "take",
            "only",
            "little",
            "work",
            "know",
            "place",
            "years",
            "live",
            "me",
            "back",
            "give",
            "most",
            "very",
            "after",
            "thing",
            "our",
            "just",
            "name",
            "good",
            "sentence",
            "man",
            "think",
            "say",
            "great",
            "where",
            "help",
            "through",
            "much",
            "before",
            "line",
            "right",
            "too",
            "means",
            "old",
            "any",
            "same",
            "tell",
            "boy",
            "following",
            "came",
            "want",
            "show",
            "also",
            "around",
            "farm",
            "three",
            "small"
        )
    )

    private val group4 = Group(
        name = "Group 4 - 200",
        words = setOf(
            "set",
            "put",
            "end",
            "does",
            "another",
            "well",
            "large",
            "must",
            "big",
            "even",
            "such",
            "because",
            "turn",
            "here",
            "why",
            "asked",
            "went",
            "men",
            "need",
            "read",
            "land",
            "different",
            "home",
            "use",
            "move",
            "try",
            "kind",
            "hand",
            "picture",
            "again",
            "change",
            "off",
            "play",
            "spell",
            "air",
            "away",
            "animals",
            "house",
            "point",
            "page",
            "letters",
            "mother",
            "answer",
            "found",
            "study",
            "still",
            "learn",
            "should",
            "America",
            "world"
        )
    )

    private val group5 = Group(
        name = "Group 5 - 250",
        words = setOf(
            "high",
            "every",
            "near",
            "add",
            "food",
            "between",
            "own",
            "below",
            "country",
            "plants",
            "last",
            "school",
            "father",
            "keep",
            "trees",
            "never",
            "started",
            "city",
            "Earth",
            "eyes",
            "light",
            "thought",
            "head",
            "under",
            "story",
            "saw",
            "left",
            "don't",
            "few",
            "while",
            "along",
            "might",
            "close",
            "something",
            "seemed",
            "next",
            "hard",
            "open",
            "example",
            "beginning",
            "life",
            "always",
            "these",
            "both",
            "paper",
            "together",
            "got",
            "group",
            "often",
            "run"
        )
    )

    private val group6 = Group(
        name = "Group 6 - 300",
        words = setOf(
            "important",
            "until",
            "children",
            "side",
            "feet",
            "car",
            "miles",
            "night",
            "walked",
            "white",
            "sea",
            "began",
            "grow",
            "took",
            "river",
            "four",
            "carry",
            "state",
            "once",
            "book",
            "hear",
            "stop",
            "without",
            "second",
            "later",
            "miss",
            "idea",
            "enough",
            "eat",
            "face",
            "watch",
            "far",
            "Indians",
            "really",
            "almost",
            "let",
            "above",
            "girl",
            "sometimes",
            "mountains",
            "cut",
            "young",
            "talk",
            "soon",
            "list",
            "song",
            "being",
            "leave",
            "family",
            "it's"
        )
    )

    private val group7 = Group(
        name = "Group 7 - 350",
        words = setOf(
            "body",
            "music",
            "color",
            "stand",
            "sun",
            "questions",
            "fish",
            "area",
            "mark",
            "dog",
            "horse",
            "birds",
            "problem",
            "complete",
            "room",
            "knew",
            "since",
            "ever",
            "piece",
            "told",
            "usually",
            "didn't",
            "friends",
            "easy",
            "heard",
            "order",
            "red",
            "door",
            "sure",
            "become",
            "top",
            "ship",
            "across",
            "today",
            "during",
            "short",
            "better",
            "best",
            "however",
            "low",
            "hours",
            "black",
            "products",
            "happened",
            "whole",
            "measure",
            "remember",
            "early",
            "waves",
            "reached"
        )
    )

    private val group8 = Group(
        name = "Group 8 - 400",
        words = setOf(
            "listen",
            "wind",
            "rock",
            "space",
            "covered",
            "fast",
            "several",
            "hold",
            "himself",
            "toward",
            "five",
            "step",
            "morning",
            "passed",
            "vowel",
            "true",
            "hundred",
            "against",
            "pattern",
            "numeral",
            "table",
            "north",
            "slowly",
            "money",
            "map",
            "busy",
            "pulled",
            "draw",
            "voice",
            "seen",
            "cold",
            "cried",
            "plan",
            "notice",
            "south",
            "sing",
            "war",
            "ground",
            "fall",
            "king",
            "town",
            "I'll",
            "unit",
            "figure",
            "certain",
            "field",
            "travel",
            "wood",
            "fire",
            "upon"
        )
    )

    private val newWords: Set<String> = emptySet()

    private val allWords: Set<String> = setOf(
        "a",
        "about",
        "again",
        "all",
        "am",
        "an",
        "and",
        "any",
        "are",
        "as",
        "ate",
        "away",
        "be",
        "because",
        "been",
        "before",
        "best",
        "big",
        "black",
        "blue",
        "brown",
        "but",
        "by",
        "call",
        "came",
        "cold",
        "come",
        "did",
        "do",
        "does",
        "done",
        "down",
        "eat",
        "eight",
        "every",
        "fall",
        "far",
        "find",
        "five",
        "fly",
        "from",
        "for",
        "four",
        "funny",
        "gave",
        "get",
        "give",
        "goes",
        "going",
        "good",
        "green",
        "grey",
        "had",
        "has",
        "have",
        "he",
        "help",
        "her",
        "here",
        "him",
        "his",
        "how",
        "I",
        "if",
        "in",
        "into",
        "its",
        "jump",
        "just",
        "kind",
        "laugh",
        "let",
        "like",
        "little",
        "look",
        "made",
        "me",
        "must",
        "new",
        "nine",
        "no",
        "not",
        "now",
        "of",
        "off",
        "on",
        "one",
        "orange",
        "our",
        "out",
        "pink",
        "play",
        "please",
        "pretty",
        "purple",
        "ran",
        "red",
        "ride",
        "run",
        "said",
        "saw",
        "say",
        "see",
        "seven",
        "shall",
        "she",
        "six",
        "so",
        "soon",
        "stop",
        "take",
        "ten",
        "that",
        "there",
        "they",
        "this",
        "three",
        "to",
        "too",
        "two",
        "up",
        "want",
        "was",
        "we",
        "well",
        "went",
        "what",
        "when",
        "where",
        "which",
        "white",
        "who",
        "why",
        "will",
        "with",
        "yes",
        "zero",

        "hold",
        "old",
        "us",
        "carry",
        "hot",
        "pull",
        "walk",
        "draw",
        "keep",
        "read",
        "your",
        "fast",
        "light",

        "after",
        "make",
        "ask",
        "wish",
        "first",
        "pick",
        "show",
        "around",
        "got",
        "right",
        "tell",
        "better",
        "hurt",
        "try",
        "upon",
        "could",
        "live",
        "always",
        "wash",
        "don't",
        "may",

        "or",
        "these",
        "drink",
        "once",

        "put",
        "full",
        "found",
        "sing",

        "round",
        "cut",
        "grow",
        "them",

        "sit",
        "use",
        "long",
        "were",

        "then",
        "both",
        "many",
        "work",

        "bring",
        "myself",
        "own",
        "thank",

        "buy",
        "never",
        "sleep",
        "their",

        "clean",
        "only",
        "small",
        "think",

        "know",
        "open",
        "some",
        "those",

        "much",
        "over",
        "start",
        "today",

        "together",
        "write",
        "much",
        "would",
        "under",
        "boy",
        "girl",
        "other",
        "very",
        "day",
        "some",
        "warm",
        "know",
        "their",
        "would",
        "man",
        "very"
    )
}
