package io.github.nullifythis.android.flashcards

import kotlin.random.Random

object Words {

    fun createRandomizedList(): List<String> {
        val randomizedList = mutableListOf<String>()
        val allWordsList = allWords.toMutableList()
        while (allWordsList.isNotEmpty()) {
            val nextIndex = Random.nextInt(0, allWordsList.size)
            val nextWord = allWordsList.removeAt(nextIndex)
            randomizedList.add(nextWord)
        }
        return randomizedList
    }

    private val allWords: Set<String> = setOf(
        "a",
        "all",
        "am",
        "an",
        "and",
        "are",
        "as",
        "be",
        "because",
        "big",
        "black",
        "blue",
        "brown",
        "but",
        "by",
        "came",
        "come",
        "did",
        "do",
        "eat",
        "eight",
        "five",
        "from",
        "for",
        "four",
        "funny",
        "get",
        "give",
        "good",
        "green",
        "grey",
        "had",
        "have",
        "he",
        "help",
        "her",
        "here",
        "his",
        "how",
        "I",
        "in",
        "into",
        "jump",
        "like",
        "little",
        "look",
        "me",
        "nine",
        "no",
        "not",
        "now",
        "of",
        "on",
        "one",
        "orange",
        "out",
        "pink",
        "play",
        "please",
        "purple",
        "ran",
        "red",
        "run",
        "said",
        "saw",
        "say",
        "see",
        "seven",
        "she",
        "six",
        "so",
        "soon",
        "ten",
        "this",
        "three",
        "to",
        "too",
        "two",
        "up",
        "want",
        "was",
        "we",
        "went",
        "what",
        "where",
        "white",
        "who",
        "why",
        "will",
        "yes",
        "zero",
    )
}
